# Generated by Django 3.2.12 on 2023-03-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/image/gallery/')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('Created_by', models.TextField(blank=True, max_length=200)),
                ('updated_by', models.TextField(blank=True, max_length=200)),
            ],
        ),
    ]
