# Generated by Django 3.2.12 on 2023-03-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteers',
            name='city',
            field=models.CharField(default='Saharanpur', max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='region',
            field=models.CharField(default='Uttar Pradesh', max_length=100),
        ),
    ]
