# Generated by Django 3.2.12 on 2023-03-17 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.CITIES_COUNTRY_MODEL),
        migrations.swappable_dependency(settings.CITIES_CITY_MODEL),
        ('cities', '0012_auto_20230314_1101'),
        ('account', '0002_auto_20230317_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteers',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.CITIES_CITY_MODEL),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.CITIES_COUNTRY_MODEL),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='pincode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.region'),
        ),
    ]
