# Generated by Django 3.2.12 on 2023-03-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20230320_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteers',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='education',
            field=models.CharField(choices=[('undergraduate ', 'Undergraduate '), ('postgraduate', 'Postgraduate'), ('other', 'Other')], max_length=32, verbose_name='Choose your Education'),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='image',
            field=models.ImageField(null=True, upload_to='static/account/image/volunteers/'),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='region',
            field=models.CharField(max_length=100),
        ),
    ]
