# Generated by Django 3.2.12 on 2023-03-31 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_donation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='pan_card',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='pay_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='Certificate_80G',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Certificate_80G_no', models.CharField(max_length=200)),
                ('pdf_file', models.FileField(upload_to='static/account/pdf/')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('Created_by', models.CharField(blank=True, max_length=200)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('donater', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.donation')),
            ],
        ),
    ]
