# Generated by Django 3.2.12 on 2023-03-14 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_gallery_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('education', models.CharField(choices=[('undergraduate ', 'Undergraduate '), ('postgraduate', 'Postgraduate'), ('other', 'Other')], default='Undergraduate', max_length=32, verbose_name='Choose your Education')),
                ('image', models.ImageField(upload_to='static/account/image/volunteers/')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=20)),
                ('visible_flag', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('Created_by', models.TextField(blank=True, max_length=200)),
                ('updated_by', models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='gallery',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Social_Voluteers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(choices=[('fa-facebook-f ', 'Facebook '), ('fa-instagram', 'Instagram'), ('fa-linkedin-in', 'LinkedIn'), ('fa-twitter', 'Twitter')], default='Facebook', max_length=32, verbose_name='Choose your social media account')),
                ('url', models.URLField(max_length=300)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('Created_by', models.TextField(blank=True, max_length=200)),
                ('updated_by', models.TextField(blank=True, max_length=200)),
                ('volunteers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.volunteers')),
            ],
        ),
    ]
