# Generated by Django 3.2.12 on 2023-03-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20230321_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteers',
            name='image',
            field=models.ImageField(upload_to='static/account/image/volunteers/'),
        ),
    ]
