# Generated by Django 3.2.12 on 2023-03-14 05:09

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20230314_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteers',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
