# Generated by Django 3.2.12 on 2023-04-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_donation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='pay_status',
            field=models.BooleanField(default=False),
        ),
    ]
