# Generated by Django 3.2.12 on 2023-04-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_donation_pay_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(default=121, max_length=300),
            preserve_default=False,
        ),
    ]
