# Generated by Django 3.2.12 on 2023-03-26 06:27

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='donation',
            name='campaigns',
            field=models.ForeignKey(default='Education', on_delete=django.db.models.deletion.CASCADE, to='account.feature_campaigns'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='education',
            field=models.CharField(choices=[('undergraduate ', 'Undergraduate '), ('postgraduate', 'Postgraduate'), ('other', 'Other')], default='Undergraduate', max_length=32, verbose_name='Choose your Education'),
        ),
    ]
