# Generated by Django 4.1.7 on 2023-05-16 05:07

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_gallery_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('amount', models.IntegerField()),
                ('pan_card', models.CharField(max_length=100)),
                ('pay_id', models.CharField(blank=True, max_length=200)),
                ('Certificate_80G', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('Created_by', models.CharField(blank=True, max_length=200)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('campaigns', models.ForeignKey(default='Education', on_delete=django.db.models.deletion.CASCADE, to='account.feature_campaigns')),
            ],
        ),
        migrations.AlterField(
            model_name='certificate_80g',
            name='donater',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.donations'),
        ),
    ]
