# Generated by Django 4.1.7 on 2023-05-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_donations_alter_certificate_80g_donater'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='pay_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('net banking', 'Net Banking')], default='green', max_length=11),
        ),
    ]
