# Generated by Django 3.2.12 on 2023-03-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20230326_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='reference',
            field=models.IntegerField(null=True),
        ),
    ]
