# Generated by Django 3.2.12 on 2023-03-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_donation_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='reference',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
