# Generated by Django 4.1.7 on 2023-05-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_users_alter_donations_pay_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='pay_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Cheque', 'Cheque'), ('Net Banking', 'Net Banking')], default='upi', max_length=11),
        ),
    ]
