# Generated by Django 3.2.12 on 2023-03-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_donation_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='Certificate_80G',
            field=models.BooleanField(default=False),
        ),
    ]
